env:
  - DB=postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickwand-dev -qq -y

install:
  - bundle install --path vendor/bundle
  - cd lineman
  - npm install -g bower
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager start
  - npm install
  - bower install

branches:
  only:
    - 'master'
    - 'production'
    - /^[0-9]+\.[0-9]+$/
rvm:
  - 2.2.0

before_script:
  - cp config/database.yml.$DB config/database.yml
  - bundle exec rake db:setup RAILS_ENV=test
  #- nohup bash -c "webdriver-manager start 2>&1 &"
  # start rails s for cuckes to hit 

#script: "bundle exec rake travis"
script: cd lineman && 

addons:
  postgresql: "9.4"
