env:
  - DB=postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickwand-dev -qq -y
  - webdriver-manager update --standalone

install:
  - bundle install --path vendor/bundle
  - cd lineman && npm install
  - npm install -g bower
  - cd lineman && bower install

branches:
  only:
    - 'master'
    - 'production'
    - /^[0-9]+\.[0-9]+$/
rvm:
  - 2.2.0

before_script:
  - cp config/database.yml.$DB config/database.yml
  - bundle exec rake db:setup RAILS_ENV=test
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "webdriver-manager start 2>&1 &"

#script: "bundle exec rake travis"
script: cd lineman && 

addons:
  postgresql: "9.4"
